# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"1\n\x08Greeting\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"1\n\x0cGreetRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"\x1f\n\rGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\":\n\x15GreetManyTimesRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"(\n\x16GreetManyTimesResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"5\n\x10LongGreetRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"#\n\x11LongGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"9\n\x14GreetEveryoneRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"\'\n\x15GreetEveryoneResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"=\n\x18GreetWithDeadlineRequest\x12!\n\x08greeting\x18\x01 \x01(\x0b\x32\x0f.greet.Greeting\"+\n\x19GreetWithDeadlineResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x87\x03\n\x0cGreetService\x12\x34\n\x05Greet\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse\"\x00\x12X\n\x11GreetWithDeadline\x12\x1f.greet.GreetWithDeadlineRequest\x1a .greet.GreetWithDeadlineResponse\"\x00\x12Q\n\x0eGreetManyTimes\x12\x1c.greet.GreetManyTimesRequest\x1a\x1d.greet.GreetManyTimesResponse\"\x00\x30\x01\x12\x42\n\tLongGreet\x12\x17.greet.LongGreetRequest\x1a\x18.greet.LongGreetResponse\"\x00(\x01\x12P\n\rGreetEveryone\x12\x1b.greet.GreetEveryoneRequest\x1a\x1c.greet.GreetEveryoneResponse\"\x00(\x01\x30\x01\x42\x0fZ\rgreet/greetpbb\x06proto3')



_GREETING = DESCRIPTOR.message_types_by_name['Greeting']
_GREETREQUEST = DESCRIPTOR.message_types_by_name['GreetRequest']
_GREETRESPONSE = DESCRIPTOR.message_types_by_name['GreetResponse']
_GREETMANYTIMESREQUEST = DESCRIPTOR.message_types_by_name['GreetManyTimesRequest']
_GREETMANYTIMESRESPONSE = DESCRIPTOR.message_types_by_name['GreetManyTimesResponse']
_LONGGREETREQUEST = DESCRIPTOR.message_types_by_name['LongGreetRequest']
_LONGGREETRESPONSE = DESCRIPTOR.message_types_by_name['LongGreetResponse']
_GREETEVERYONEREQUEST = DESCRIPTOR.message_types_by_name['GreetEveryoneRequest']
_GREETEVERYONERESPONSE = DESCRIPTOR.message_types_by_name['GreetEveryoneResponse']
_GREETWITHDEADLINEREQUEST = DESCRIPTOR.message_types_by_name['GreetWithDeadlineRequest']
_GREETWITHDEADLINERESPONSE = DESCRIPTOR.message_types_by_name['GreetWithDeadlineResponse']
Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.Greeting)
  })
_sym_db.RegisterMessage(Greeting)

GreetRequest = _reflection.GeneratedProtocolMessageType('GreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetRequest)
  })
_sym_db.RegisterMessage(GreetRequest)

GreetResponse = _reflection.GeneratedProtocolMessageType('GreetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETRESPONSE,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetResponse)
  })
_sym_db.RegisterMessage(GreetResponse)

GreetManyTimesRequest = _reflection.GeneratedProtocolMessageType('GreetManyTimesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETMANYTIMESREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetManyTimesRequest)
  })
_sym_db.RegisterMessage(GreetManyTimesRequest)

GreetManyTimesResponse = _reflection.GeneratedProtocolMessageType('GreetManyTimesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETMANYTIMESRESPONSE,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetManyTimesResponse)
  })
_sym_db.RegisterMessage(GreetManyTimesResponse)

LongGreetRequest = _reflection.GeneratedProtocolMessageType('LongGreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _LONGGREETREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.LongGreetRequest)
  })
_sym_db.RegisterMessage(LongGreetRequest)

LongGreetResponse = _reflection.GeneratedProtocolMessageType('LongGreetResponse', (_message.Message,), {
  'DESCRIPTOR' : _LONGGREETRESPONSE,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.LongGreetResponse)
  })
_sym_db.RegisterMessage(LongGreetResponse)

GreetEveryoneRequest = _reflection.GeneratedProtocolMessageType('GreetEveryoneRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETEVERYONEREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetEveryoneRequest)
  })
_sym_db.RegisterMessage(GreetEveryoneRequest)

GreetEveryoneResponse = _reflection.GeneratedProtocolMessageType('GreetEveryoneResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETEVERYONERESPONSE,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetEveryoneResponse)
  })
_sym_db.RegisterMessage(GreetEveryoneResponse)

GreetWithDeadlineRequest = _reflection.GeneratedProtocolMessageType('GreetWithDeadlineRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETWITHDEADLINEREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetWithDeadlineRequest)
  })
_sym_db.RegisterMessage(GreetWithDeadlineRequest)

GreetWithDeadlineResponse = _reflection.GeneratedProtocolMessageType('GreetWithDeadlineResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETWITHDEADLINERESPONSE,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetWithDeadlineResponse)
  })
_sym_db.RegisterMessage(GreetWithDeadlineResponse)

_GREETSERVICE = DESCRIPTOR.services_by_name['GreetService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\rgreet/greetpb'
  _GREETING._serialized_start=22
  _GREETING._serialized_end=71
  _GREETREQUEST._serialized_start=73
  _GREETREQUEST._serialized_end=122
  _GREETRESPONSE._serialized_start=124
  _GREETRESPONSE._serialized_end=155
  _GREETMANYTIMESREQUEST._serialized_start=157
  _GREETMANYTIMESREQUEST._serialized_end=215
  _GREETMANYTIMESRESPONSE._serialized_start=217
  _GREETMANYTIMESRESPONSE._serialized_end=257
  _LONGGREETREQUEST._serialized_start=259
  _LONGGREETREQUEST._serialized_end=312
  _LONGGREETRESPONSE._serialized_start=314
  _LONGGREETRESPONSE._serialized_end=349
  _GREETEVERYONEREQUEST._serialized_start=351
  _GREETEVERYONEREQUEST._serialized_end=408
  _GREETEVERYONERESPONSE._serialized_start=410
  _GREETEVERYONERESPONSE._serialized_end=449
  _GREETWITHDEADLINEREQUEST._serialized_start=451
  _GREETWITHDEADLINEREQUEST._serialized_end=512
  _GREETWITHDEADLINERESPONSE._serialized_start=514
  _GREETWITHDEADLINERESPONSE._serialized_end=557
  _GREETSERVICE._serialized_start=560
  _GREETSERVICE._serialized_end=951
# @@protoc_insertion_point(module_scope)
